version: '3.9'
services:
  www:
    image: ranadeeppolavarapu/nginx-http3
    container_name: www
    restart: unless-stopped
    working_dir: /www
    environment:
      TZ: Europe/Warsaw
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - type: bind
        source: "/mnt"
        target: /www/file
        read_only: true
      - ./www/nginx.conf:/etc/nginx/nginx.conf
      - ./www/index.html:/www/index.html
      - ./www/build/:/www/resources/
      - ./www/cert.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./www/private.key:/etc/ssl/private/nginx-selfsigned.key
    networks:
      - simple-media-server-network
  php:
    build:
      context: ./php
      dockerfile: Dockerfile.dev
    image: simple-media-server/php-ffmpeg:dev
    container_name: php
    restart: unless-stopped
    working_dir: /www
    environment:
      DB_HOST: mariadb
      DB_NAME: simple-media-server
      DB_USER: simple-media-server
      DB_PASSWORD: zaq1@WSX
    volumes:
      - type: bind
        source: "/mnt"
        target: /www/file
        read_only: true
      - ./php/api/:/www/api/
    networks:
      - simple-media-server-network
  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    image: simple-media-server/mariadb
    container_name: mariadb
    restart: unless-stopped
    ports:
     - "3306:3306"
    networks:
      - simple-media-server-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      TZ: Europe/Warsaw
      PMA_HOST: mariadb
      PMA_USER: simple-media-server
      PMA_PASSWORD: zaq1@WSX
    ports:
      - "8080:80"
    networks:
      - simple-media-server-network
networks:
  simple-media-server-network:
    driver: bridge
