version: '3.9'
services:
  www:
    image: nginx:mainline
    container_name: www
    restart: unless-stopped
    working_dir: /www
    environment:
      - TZ:Europe/Warsaw
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: "/mnt"
        target: /www/file
        read_only: true
      - ./www/nginx.conf:/etc/nginx/nginx.conf
      - ./www/index.html:/www/index.html
      - ./www/build/:/www/resources/
    networks:
      - simple-media-server-network
  php:
    build:
      context: ./php
      dockerfile: Dockerfile.dev
    image: simple-media-server/php-ffmpeg:dev
    container_name: php
    restart: unless-stopped
    working_dir: /www
    environment:
      - TZ:Europe/Warsaw
    volumes:
      - type: bind
        source: "/mnt"
        target: /www/file
        read_only: true
      - ./php/api/:/www/api/
    networks:
      - simple-media-server-network
networks:
  simple-media-server-network:
    driver: bridge
