version: '3.9'
services:
  www:
    build:
      context: ./www
      dockerfile: Dockerfile
    image: simple-media-server/www:prod
    container_name: www
    restart: unless-stopped
    working_dir: /www
    environment:
      TZ: Europe/Warsaw
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: "/mnt"
        target: /www/file
        read_only: true
    networks:
      - simple-media-server-network
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: simple-media-server/php-ffmpeg:prod
    container_name: php
    restart: unless-stopped
    working_dir: /www
    environment:
      DB_HOST: mariadb
      DB_NAME: simple-media-server
      DB_USER: simple-media-server
      DB_PASSWORD: zaq1@WSX
    volumes:
      - type: bind
        source: "/mnt"
        target: /www/file
        read_only: true
    networks:
      - simple-media-server-network
  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    image: simple-media-server/mariadb
    container_name: mariadb
    restart: unless-stopped
    networks:
      - simple-media-server-network
networks:
  simple-media-server-network:
    driver: bridge
