version: '3.9'
services:
  www:
    build:
      context: ./www
      dockerfile: Dockerfile
    image: simple-media-server/www
    container_name: www
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: "/mnt/e/Z telefonu"
        target: /www/file
        read_only: true
    networks:
      - simple-media-server-network
  thumbnails:
    build:
      context: ./thumbnails
      dockerfile: Dockerfile
    image: simple-media-server/thumbnails
    container_name: thumbnails
    restart: unless-stopped
    volumes:
      - type: bind
        source: "/home/szymon/cache"
        target: /app/cache
      - type: bind
        source: "/mnt/e/Z telefonu"
        target: /app/files
        read_only: true
    networks:
      - simple-media-server-network
networks:
  simple-media-server-network:
    driver: bridge
