version: '3.9'
services:
  www:
    build:
      context: ./www
      dockerfile: Dockerfile
    image: simple-media-server/www:prod
    container_name: www
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: "/mnt"
        target: /www/file
        read_only: true
    networks:
      - simple-media-server-network
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: simple-media-server/php-ffmpeg:prod
    container_name: php
    restart: unless-stopped
    working_dir: /www
    environment:
      - TZ:Europe/Warsaw
    volumes:
      - type: bind
        source: "/mnt"
        target: /www/file
        read_only: true
    networks:
      - simple-media-server-network
networks:
  simple-media-server-network:
    driver: bridge
