name: Build Docker Image
on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
jobs:
  push:
    name: "simple-media-server:docker"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          tags: |
            ghcr.io/panszelescik/simple-media-server:docker
